export {default as About} from "./About";
export {default as ContactForm} from "./ContactForm";
export {default as Education} from "./Education";
export {default as Experience} from "./Experience";
export {default as Hero} from "./Hero";
export {default as Navbar} from "./Navbar";
export {default as Projects} from "./Projects";
export {default as Technologies} from "./Technologies";
export {default as WorkInProgress} from "./WorkInProgress";